name: benchmark_test
description: A tool to integrate benchmarking into your development and testing workflow.
version: 0.0.2
homepage: https://github.com/appsup-dart/benchmark_test
repository: https://github.com/appsup-dart/benchmark_test
funding:
 - https://github.com/sponsors/rbellens


environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.21.0
  test_api: '>=0.6.0 <0.8.0'
  meta: ^1.14.0

dev_dependencies:
  lints: ^6.0.0
  melos: ^7.0.0


melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    preversion: 
      exec: dart test -j 1  
