name: benchmark_test
description: A tool to integrate benchmarking into your development and testing workflow.
version: 0.1.2
homepage: https://github.com/appsup-dart/benchmark_test
repository: https://github.com/appsup-dart/benchmark_test
funding:
 - https://github.com/sponsors/rbellens

executables:
  benchmark_test:

environment:
  sdk: ^3.0.0

dependencies:
  test: ^1.21.0
  test_api: '>=0.6.0 <0.8.0'
  meta: ^1.14.0
  ansi: ^0.4.2
  args: ^2.5.0
  vm_service: '>=14.0.0 <16.0.0'

dev_dependencies:
  lints: ^6.0.0
  melos: ^7.0.0


melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false
      hooks:
        pre:
          exec: dart test -j 1
